apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "traefik.fullname" . }}-dashboard-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik-v2"
spec:
  basicAuth:
    secret: dashboard-users