apiVersion: v1
kind: Secret
metadata:
  name: dashboard-users
  namespace: traefik
data:
  users: |2
    d2hvZ2FuMDA6JGFwcjEkLjBjckN5dUwkd1FDN2d0N1A2S2dnMS9RL2t0dVZxLgp3aG9nYW46JGFwcjEkaHNmYllNMWckQmlqanNmaTMxY1EvWnRSNmoudTV6Lgo=